# Generated by Django 4.2.7 on 2023-11-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lianjia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
        migrations.AlterModelTable(
            name='district',
            table='district',
        ),
        migrations.AlterModelTable(
            name='houses',
            table='houses',
        ),
        migrations.AlterModelTable(
            name='village',
            table='village',
        ),
    ]
