# Generated by Django 4.2.7 on 2023-11-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lianjia', '0002_alter_city_table_alter_district_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houses',
            old_name='house_id',
            new_name='id',
        ),
    ]
